-- Buat tabel FAQ
create table if not exists faq (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default now()
);

-- Buat tabel Chats
create table if not exists chats (
  id bigint generated by default as identity primary key,
  wa_id text not null,
  sender text not null check (sender in ('customer', 'agent')),
  message text not null,
  created_at timestamp with time zone default now()
);

-- Index untuk ngeliat history per customer
create index if not exists chats_wa_id_idx on chats (wa_id);
